/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 spinner1.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import spinner from "./../assets/spinner2.glb"
export function Spinner(props) {
  const { nodes, materials } = useGLTF(spinner)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 4.52]}>
        <pointLight intensity={5}  rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.outerRingOfLight.geometry} material={materials.innerRing} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.gemPlaceholder.geometry} material={materials.gemPlaceholder} position={[0, 3.2, 0.33]} rotation={[Math.PI / 2, 0, 0]} scale={0.2} />
      <mesh geometry={nodes.Plane.geometry} material={materials.gemPlaceholder} position={[0, 3.19, 0.34]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.gemLight1.geometry} material={materials.gemLight} position={[-0.19, 3.09, 0.36]} scale={0.06} />
      <mesh geometry={nodes.gemLight2.geometry} material={materials.gemLight} position={[0.18, 3.09, 0.36]} scale={0.06} />
      <mesh geometry={nodes.backSide.geometry} material={materials.gemLight} rotation={[Math.PI / 2, 0, 0]} scale={2.72} />
      <mesh geometry={nodes.Center.geometry} material={materials.Center} position={[0, 0, 0.19]} rotation={[Math.PI / 2, 0, 0]} scale={[0.88, 0.38, 0.88]} />
      <mesh geometry={nodes.innerRing.geometry} material={materials.innerRing} position={[0, 0, 0.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.91} />
      <mesh geometry={nodes.outerLight1.geometry} material={materials.outerLight} position={[1.6, 2.82, 0.28]} rotation={[-Math.PI / 2, 0.52, -Math.PI]} scale={0.36} />
      <mesh geometry={nodes.outerLight3.geometry} material={materials.outerLight} rotation={[-Math.PI / 2, 1.05, -Math.PI]} scale={0.36} />
      <mesh geometry={nodes.outerLight5.geometry} material={materials.outerLight} rotation={[Math.PI / 2, 1.04, 0]} scale={0.36} />
      <mesh geometry={nodes.outerLight6.geometry} material={materials.outerLight} rotation={[Math.PI / 2, 0, 0]} scale={0.36} />
      <mesh geometry={nodes.outerLight2.geometry} material={materials.outerLight} rotation={[1.57, 1.57, 0]} scale={0.36} />
      <mesh geometry={nodes.outerLight4.geometry} material={materials.outerLight} rotation={[Math.PI / 2, 0.52, 0]} scale={0.36} />
      <mesh geometry={nodes.outerRing.geometry} material={materials.outerLight} position={[0, 0, 0.29]} rotation={[Math.PI / 2, 0, 0]} scale={2.91} />
      <mesh geometry={nodes.Sphere023.geometry} material={materials.stone} position={[0, 3.2, 0.33]} rotation={[Math.PI / 2, 0, 0]} scale={0.21} />
      <mesh geometry={nodes.gemAtTop001.geometry} material={materials.Diamond} position={[0.01, 3.2, 0.36]} rotation={[Math.PI / 2, 0, 0]} scale={0.19} />
      <mesh geometry={nodes.innerDiamond1.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[Math.PI / 2, 0, 0]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond3.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[Math.PI / 2, -1.57, 0]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond2.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond4.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond5.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[Math.PI / 2, -Math.PI / 6, 0]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond6.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[-Math.PI / 2, -Math.PI / 3, -Math.PI]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond7.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[-Math.PI / 2, Math.PI / 6, -Math.PI]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond8.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[Math.PI / 2, Math.PI / 3, 0]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond9.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[Math.PI / 2, -Math.PI / 3, 0]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond10.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[-Math.PI / 2, -Math.PI / 6, Math.PI]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond11.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[-Math.PI / 2, Math.PI / 3, -Math.PI]} scale={0.08} />
      <mesh geometry={nodes.innerDiamond12.geometry} material={materials.Diamond} position={[0, 0, 0.19]} rotation={[Math.PI / 2, Math.PI / 6, 0]} scale={0.08} />
      <mesh geometry={nodes.display.geometry} material={materials.display} position={[0, 0, 0.28]} rotation={[Math.PI / 2, 0, 0]} scale={1.35} />
      <mesh geometry={nodes.Sphere058.geometry} material={materials.stone} />
      <mesh geometry={nodes.Sphere058_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload(spinner)
