/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 CARD 3.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/CARD 3.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="final_for_render_">
        <group name="base_parent_" position={[0, -0.09, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.73}>
          <mesh name="backHeart" geometry={nodes.backHeart.geometry} material={materials.QR} position={[-0.78, -0.04, 1.61]} rotation={[0, 0, -Math.PI]} scale={[0.65, 2.95, 0.65]} />
          <mesh name="backLogo" geometry={nodes.backLogo.geometry} material={materials['Material.007']} position={[-0.22, -0.03, 0]} rotation={[Math.PI, 0, 0]} scale={[-2.27, -3.2, -2.27]} />
          <mesh name="backText1" geometry={nodes.backText1.geometry} material={materials.text} position={[0.39, -0.05, 1.43]} rotation={[-Math.PI, 0, 0]} scale={[-0.13, -1.95, -0.13]} />
          <mesh name="backText2" geometry={nodes.backText2.geometry} material={materials.text} position={[0.36, -0.05, 1.56]} rotation={[-Math.PI, 0, 0]} scale={[-0.1, -1.56, -0.1]} />
          <mesh name="BackText3" geometry={nodes.BackText3.geometry} material={materials.text} position={[0.7, -0.05, 1.75]} rotation={[-Math.PI, 0, 0]} scale={[-0.13, -1.91, -0.13]} />
          <mesh name="backText4" geometry={nodes.backText4.geometry} material={materials.text} position={[0.49, -0.05, 1.85]} rotation={[-Math.PI, 0, 0]} scale={[-0.1, -1.08, -0.1]} />
          <mesh name="forwardQR" geometry={nodes.forwardQR.geometry} material={materials.text} position={[0.8, 0.04, 1.66]} scale={[0.57, 2.34, 0.57]} />
          <mesh name="forwardText1" geometry={nodes.forwardText1.geometry} material={materials.text} position={[-0.12, 0.04, 1.39]} scale={[0.11, 1.6, 0.11]} />
          <mesh name="forwardText2" geometry={nodes.forwardText2.geometry} material={materials.text} position={[-0.37, 0.04, 1.51]} scale={[0.15, 1.57, 0.15]} />
          <mesh name="forwardText3" geometry={nodes.forwardText3.geometry} material={materials.text} position={[-0.41, 0.04, 1.65]} scale={[0.1, 1.55, 0.1]} />
          <mesh name="forwardText4" geometry={nodes.forwardText4.geometry} material={materials.text} position={[-0.36, 0.04, 1.77]} scale={[0.1, 1.55, 0.1]} />
          <mesh name="forwardText5" geometry={nodes.forwardText5.geometry} material={materials.text} position={[-0.74, 0.05, 1.87]} scale={[0.1, 1.57, 0.1]} />
          <mesh name="profile" geometry={nodes.profile.geometry} material={materials.profile} position={[0.02, 0.05, -0.15]} scale={[0.77, 0.05, 0.77]} />
          <mesh name="RoundBorder" geometry={nodes.RoundBorder.geometry} material={materials.RoundBorder} position={[0.02, 0.05, -0.15]} scale={[0.71, 0.05, 0.71]} />
        </group>
        <mesh name="bottomHalf" geometry={nodes.bottomHalf.geometry} material={materials.RoundBorder} position={[0, -1.3, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.48, 0.22]} />
        <mesh name="cardBody" geometry={nodes.cardBody.geometry} material={materials.body} position={[0, -0.14, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.84, 0.48, 1.12]} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.004']} position={[-0.01, 0.91, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.23} />
      </group>
    </group>
  )
}

useGLTF.preload('/CARD 3.glb')
