/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 my.glb
*/
import { extend } from '@react-three/fiber'
import * as THREE from 'three'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import React, { useRef } from 'react'
import { useTexture } from '@react-three/drei'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import multi from "./../../assets/p.jpg"
import { useState,useEffect } from 'react'
import { useLoader } from '@react-three/fiber'  
import { MeshStandardMaterial } from 'three'
import {TextGeometry} from "three/examples/jsm/geometries/TextGeometry"
import { FontLoader } from 'three/examples/jsm/loaders/FontLoader'
import fo from "./../../assets/Adobe Garamond Pro Bold_Regular.typeface.json"
extend({TextGeometry})
export default function Card(props) {
  const group = useRef()
  useFrame((state, delta) => (group.current.rotation.y += delta/3))
  const { nodes, materials, animations } = useGLTF('/rev.glb')
  const { actions } = useAnimations(animations, group)
  const [video] = useState(() => Object.assign(document.createElement('video'), { src: '/text.mp4', crossOrigin: 'Anonymous', loop: true, muted: true }))
  useEffect(() => void video.play(), [video])
  const colorMap = useLoader(TextureLoader, multi)
  const text = useTexture("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN4AaarcsBBIx79EDp059JxdmsSBQpw1j-Z7DZLYg&s")
  console.log(nodes.forwardText1)
  const font = new FontLoader().parse(fo)
  return (
    <group scale={1.5} ref={group} {...props} dispose={null}>
      <group name="final_for_render_">
        <group name="base_parent_" position={[0, -0.09, 0.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.73}>
          <mesh name="backHeart" geometry={nodes.backHeart.geometry} material={materials.QR} position={[-0.78, -0.04, 1.61]} rotation={[0, 0, -Math.PI]} scale={[0.65, 2.95, 0.65]} />
          <mesh name="backLogo" geometry={nodes.backLogo.geometry} material={materials['Material.007']} position={[-0.22, -0.06, 0]} rotation={[Math.PI, 0, 0]} scale={[-2.27, -3.2, -2.27]} />
          <mesh name="backText1" geometry={nodes.backText1.geometry} material={materials.text} position={[1.06, -0.05, 1.47]} rotation={[-Math.PI, 0, 0]} scale={[-0.13, -1.95, -0.13]} />
          <mesh name="backText2" geometry={nodes.backText2.geometry} material={materials.text} position={[1.06, -0.05, 1.59]} rotation={[-Math.PI, 0, 0]} scale={[-0.1, -1.56, -0.1]} />
          <mesh name="BackText3" geometry={nodes.BackText3.geometry} material={materials.text} position={[1.06, -0.05, 1.78]} rotation={[-Math.PI, 0, 0]} scale={[-0.13, -1.91, -0.13]} />
          <mesh name="backText4" geometry={nodes.backText4.geometry} material={materials.text} position={[1.06, -0.05, 1.89]} rotation={[-Math.PI, 0, 0]} scale={[-0.1, -1.08, -0.1]} />
          <mesh name="forwardQR" geometry={nodes.forwardQR.geometry} material={materials.text} position={[0.55, 0.04, 1.9]} scale={[0.57, 2.34, 0.57]} />
          <mesh name="forwardText1" rotation={[4.6,0,0]}  material={materials.text} position={[-1.03, 0.04, 1.42]}  >
          <textGeometry  args={['test', {font, size:0.1, height: 0.03,bewelThickness:0.003,bewelSize:0.015}]}/>
             {/* <textGeometry args={["Muhammad Ali",{font,height:1,bevelEnabled:false}]} /> */}
          </mesh>
          <mesh name="forwardText2" geometry={nodes.forwardText2.geometry} material={materials.text} position={[-1.03, 0.04, 1.56]} scale={[0.15, 1.57, 0.15]} />
          <mesh name="forwardText3" geometry={nodes.forwardText3.geometry} material={materials.text} position={[-1.03, 0.04, 1.69]} scale={[0.1, 1.55, 0.1]} />
          <mesh name="forwardText4" geometry={nodes.forwardText4.geometry} material={materials.text} position={[-1.03, 0.04, 1.79]} scale={[0.1, 1.55, 0.1]} />
          <mesh name="forwardText5" geometry={nodes.forwardText5.geometry} material={materials.text} position={[-1.02, 0.05, 1.9]} scale={[0.1, 1.57, 0.1]} />
          <mesh name="profile"  rotation={[0,89.55,0]}  geometry={nodes.profile.geometry} material={materials.profile} position={[0.02, 0.1, -0.15]} scale={[0.77, 0.05, 0.77]} >
            <meshStandardMaterial reflectivity={0}  map={text} toneMapped={false} transparent={false} opacity={1} />
          </mesh>
          <mesh name="RoundBorder" geometry={nodes.RoundBorder.geometry} material={materials['Material.007']} position={[0.02, 0.1, -0.15]} scale={[0.71, 0.05, 0.71]} />
        </group>
        <mesh name="bottomHalf" geometry={nodes.bottomHalf.geometry} material={materials['Material.007']} position={[0, -1.32, 0.17]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.48, 0.22]} />
        <mesh name="cardBody" geometry={nodes.cardBody.geometry} position={[0, -0.14, -0.27]} rotation={[Math.PI / 2, 0, 0]} scale={[0.84, 0.48, 1.12]} >
          <meshBasicMaterial toneMapped={false}>
            <videoTexture attach="map" args={[video]} encoding={THREE.sRGBEncoding} />
          </meshBasicMaterial>
        </mesh>
        <mesh name="RankPlace" geometry={nodes.RankPlace.geometry}  position={[0, 1.03, 0.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.48} >
        <meshStandardMaterial map={colorMap} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/rev.glb')
// font : AGaramond pro-bold 
// depth : 0.015
// extr 0.003